export function adminCopy(lang: string) {
 return lang === "zh-Hans" ? {
 createMaster:"新建主分类", createSub:"新建子分类", manageSub:"管理子分类", deleteCategory:"删除分类", deleting:"正在删除…", deleted:"分类已删除，工具已移至未分类。", confirmDelete:"我确认删除此分类。", confirmRequired:"请先确认删除。", deleteSubWarning:"此子分类将被永久删除。其工具将移至未分类，工具和记录均会保留。", deleteMasterWarning:"此主分类及其所有子分类将被永久删除。所有相关工具将移至未分类，工具和记录均会保留。", allCategories:"返回全部分类", masterLabel:"主分类", subLabel:"子分类", categoryLibrary:"分类管理", inactive:"已停用", subIntro:"管理此主分类下的子分类，让工具更容易查找。", masterIntro:"按主题整理工具。选择一个主分类来管理其子分类。", accountDirectory:"账户管理", usersIntro:"查看个人及公司用户，管理资料与访问权限。", companiesIntro:"查看公司账户，管理公司资料、方案和席位。", companyAccount:"公司账户", personalAccount:"个人账户", companyLabel:"公司", accountLabel:"账户", phoneLabel:"电话", addressLabel:"地址", websiteLabel:"网站", countryUnset:"未设置国家", planUnavailable:"方案不可用", seatsLabel:"个席位", editUser:"编辑用户", editCompany:"编辑公司", companyFilter:"按公司筛选", allUsers:"全部用户", allCompanies:"返回全部公司", sortBy:"排序", nameAsc:"姓名升序", nameDesc:"姓名降序", ownersFirst:"所有者优先", adminsFirst:"公司管理员优先", newestFirst:"最新注册优先", applyFilters:"应用筛选", viewUsers:"查看用户", title:"管理中心", users:"用户", companies:"公司", categories:"分类", intro:"管理账户、公司和工具分类。",
 search:"搜索", save:"保存", saving:"正在保存…", saved:"已保存", failed:"无法保存。请检查字段，或刷新后重试。",
 forbidden:"需要超级用户权限。", unavailable:"暂时无法加载管理数据。", create:"新建分类", edit:"编辑", active:"启用",
 displayName:"姓名", name:"名称", email:"电子邮箱", phone:"电话或手机（选填）", preferredLanguage:"语言",
 companyId:"公司 ID（个人账户留空）", companyRole:"公司角色", accountTypeId:"账户方案", isSuperAdmin:"超级用户",
 country:"国家（选填）", address:"地址（选填）", websiteUrl:"网站（选填）", seatLimit:"席位数", expiresAt:"到期时间（UTC，选填）",
 description:"描述", displayOrder:"显示顺序", masterCategoryId:"主分类 ID", master:"主分类", sub:"子分类",
 personal:"个人账户／无", browser:"跟随浏览器", member:"成员", owner:"所有者", admin:"管理员",
 previous:"上一页", next:"下一页", empty:"没有匹配的条目。", results:"条记录", hint:"身份或权限变更将注销该用户的现有会话。公司用户继承公司方案。",
 enName:"英文名称（选填）", enDescription:"英文描述（选填）", zhName:"中文名称（选填）", zhDescription:"中文描述（选填）",
 conflict:"无法保存：条目已更改、名称重复、席位不足，或会移除最后一位管理员。请检查后重试。"
 } : {
 createMaster:"New master category", createSub:"New subcategory", manageSub:"Manage subcategories", deleteCategory:"Delete category", deleting:"Deleting…", deleted:"Category deleted. Tools moved to Uncategorized.", confirmDelete:"I confirm that this category should be deleted.", confirmRequired:"Please confirm deletion first.", deleteSubWarning:"This subcategory will be permanently deleted. Its tools will move to Uncategorized. Tools and their records will be preserved.", deleteMasterWarning:"This master category and all its subcategories will be permanently deleted. All linked tools will move to Uncategorized. Tools and their records will be preserved.", allCategories:"Back to all categories", masterLabel:"Master category", subLabel:"Subcategory", categoryLibrary:"Category library", inactive:"Inactive", subIntro:"Organize the subcategories within this master category.", masterIntro:"Organize tools by topic. Choose a master category to manage its subcategories.", accountDirectory:"Account directory", usersIntro:"Review personal and company users, profile details, and access.", companiesIntro:"Manage company profiles, account plans, and available seats.", companyAccount:"Company account", personalAccount:"Personal account", companyLabel:"Company", accountLabel:"Account", phoneLabel:"Phone", addressLabel:"Address", websiteLabel:"Website", countryUnset:"Country not set", planUnavailable:"Plan unavailable", seatsLabel:"seats", editUser:"Edit user", editCompany:"Edit company", companyFilter:"Filter by company", allUsers:"All users", allCompanies:"Back to all companies", sortBy:"Sort by", nameAsc:"Name A–Z", nameDesc:"Name Z–A", ownersFirst:"Owners first", adminsFirst:"Company admins first", newestFirst:"Newest first", applyFilters:"Apply filters", viewUsers:"View users", title:"Administration", users:"Users", companies:"Companies", categories:"Categories", intro:"Manage accounts, companies, and tool categories.",
 search:"Search", save:"Save", saving:"Saving…", saved:"Saved", failed:"Could not save. Check the fields, or reload and try again.",
 forbidden:"Superuser access is required.", unavailable:"Administration data is temporarily unavailable.", create:"New category", edit:"Edit", active:"Active",
 displayName:"Name", name:"Name", email:"Email", phone:"Phone or mobile (optional)", preferredLanguage:"Language",
 companyId:"Company ID (blank for personal)", companyRole:"Company role", accountTypeId:"Account plan", isSuperAdmin:"Superuser",
 country:"Country (optional)", address:"Address (optional)", websiteUrl:"Website (optional)", seatLimit:"Seat limit", expiresAt:"Expiry (UTC, optional)",
 description:"Description", displayOrder:"Display order", masterCategoryId:"Master category ID", master:"Master categories", sub:"Subcategories",
 personal:"Personal / none", browser:"Browser default", member:"Member", owner:"Owner", admin:"Admin",
 previous:"Previous", next:"Next", empty:"No matching entries.", results:"entries", hint:"Identity or access changes sign this user out of existing sessions. Company users inherit their company plan.",
 enName:"English name (optional)", enDescription:"English description (optional)", zhName:"Chinese name (optional)", zhDescription:"Chinese description (optional)",
 conflict:"Could not save: the entry changed, a name is duplicated, seats are full, or the last administrator would be removed."
 };
}
